---

- name: Install munin-node
  apt: name={{ item }} state=present
  with_items:
   - munin-node
   - munin-plugins-extra
  tags: munin-node

- name: Configure munin-node file
  template: src=munin-node.conf.j2 dest=/etc/munin/munin-node.conf
  notify: restart munin-node
  tags: munin-node

- name: Configure munin-node
  template: src=munin-node.conf.j2 dest=/etc/munin/munin-node.conf
  notify: restart munin-node
  tags: munin-node

- name: Configure munin plugins file
  template: src=plugin-conf.d/munin-node.j2 dest=/etc/munin/plugin-conf.d/munin-node
  notify: restart munin-node
  tags: munin-node

- name: Include the redis tasks
  include: redis.yml
  when: "munin_node.external_plugins is defined and 'redis' in munin_node.external_plugins"

- name: Include the elasticsearch tasks
  include: elasticsearch.yml
  when: "munin_node.external_plugins is defined and 'elasticsearch' in munin_node.external_plugins"

- name: Enable the plugins
  file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
  with_items: munin_node.plugins
  notify: restart munin-node
  tags: munin-node
  when: munin_node.plugins is defined

