---

- stat: path=/usr/share/munin/plugins/elasticsearch-munin
  register: elasticsearch

- name: Clone the elasticsearch plugins
  git: repo=https://github.com/y-ken/munin-plugin-elasticsearch dest=/usr/share/munin/plugins/elasticsearch-munin
  tags:
    - munin-node
    - elasticsearch

- name: Copy the elasticsearch plugins
  copy: src=/usr/share/munin/plugins/elasticsearch-munin/elasticsearch_* dest=/usr/share/munin/plugins/ remote_src=True
  tags:
    - munin-node
    - elasticsearch